/*
  从 @/contents 下读目录结构，自动构建 constants.ts
*/
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { FileType } from '../types.ts';

// Replicate __dirname in ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const CONTENT_DIR = path.join(__dirname, '../content');
const OUTPUT_FILE = path.join(__dirname, '../constants.ts');
const IGNORE_FILES = ['.DS_Store', 'Thumbs.db'];

// Helper to sanitize paths for cross-platform compatibility (Windows/Mac/Linux)
const toForwardSlash = (str) => str.replace(/\\/g, '/');

/**
 * Recursively scans a directory and returns a FileNode tree
 */
function scanDirectory(dir, relativePath = '') {
  if (!fs.existsSync(dir)) {
    console.error(`Directory not found: ${dir}`);
    return [];
  }

  const items = fs.readdirSync(dir, { withFileTypes: true });
  
  // Sort: Directories first, then files alphabetical
  items.sort((a, b) => {
    if (a.isDirectory() && !b.isDirectory()) return -1;
    if (!a.isDirectory() && b.isDirectory()) return 1;
    return a.name.localeCompare(b.name);
  });

  return items
    .filter(item => !item.name.startsWith('.') && !IGNORE_FILES.includes(item.name))
    .map(item => {
      const fullPath = path.join(dir, item.name);
      // Create the virtual path (e.g., "docs/intro.md")
      const itemRelativePath = relativePath ? path.join(relativePath, item.name) : item.name;
      const virtualPath = toForwardSlash(itemRelativePath);
      
      if (item.isDirectory()) {
        return {
          name: item.name,
          type: FileType.DIRECTORY,
          path: virtualPath,
          children: scanDirectory(fullPath, itemRelativePath)
        };
      } else {
        return {
          name: item.name,
          type: FileType.FILE,
          path: virtualPath,
          content: fs.readFileSync(fullPath, 'utf-8')
        };
      }
    });
}

/**
 * Main function to generate the file
 */
function generate() {
  console.log('Scanning content directory...');
  const fileSystem = scanDirectory(CONTENT_DIR);
  
  const fileContent = `// This file is auto-generated by scripts/generate-fs.js
// Do not edit this file directly. Edit files in the 'content' folder instead.
import { FileNode, FileType } from './types';

export const VIRTUAL_FILE_SYSTEM: FileNode[] = ${JSON.stringify(fileSystem, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`✅ constants.ts updated at ${new Date().toLocaleTimeString()}`);
}

// Initial Generation
generate();

// Watch Mode
if (process.argv.includes('--watch')) {
  console.log(`👀 Watching for changes in ${CONTENT_DIR}...`);
  
  let debounceTimer;
  fs.watch(CONTENT_DIR, { recursive: true }, (eventType, filename) => {
    if (filename && !IGNORE_FILES.includes(path.basename(filename)) && !filename.startsWith('.')) {
      // Debounce to prevent multiple writes for single save
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        console.log(`Detected change in ${filename}, regenerating...`);
        generate();
      }, 100);
    }
  });
}
